-- UniMarket PostgreSQL Schema
-- 실행 주체: docker-entrypoint-initdb.d 가 POSTGRES_USER (= univmarket)로 자동 실행

-- =========================================================
-- users
-- =========================================================
CREATE TABLE users (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid          VARCHAR(128)  NOT NULL UNIQUE,
    email                 VARCHAR(255)  NOT NULL,
    display_name          VARCHAR(100),
    nickname              VARCHAR(16)   UNIQUE,
    university            VARCHAR(50),
    points                BIGINT        DEFAULT 0 NOT NULL,
    earnings              BIGINT        DEFAULT 0 NOT NULL,
    pending_earnings      BIGINT        DEFAULT 0 NOT NULL,
    total_earned          BIGINT        DEFAULT 0 NOT NULL,
    total_spent           BIGINT        DEFAULT 0 NOT NULL,
    role                  VARCHAR(10)   DEFAULT 'user' NOT NULL,
    identity_verified     BOOLEAN       DEFAULT FALSE NOT NULL,
    identity_verified_at  TIMESTAMP,
    verified_name         VARCHAR(50),
    verified_phone        VARCHAR(20),
    verified_birth        VARCHAR(6),
    banned                BOOLEAN       DEFAULT FALSE NOT NULL,
    banned_at             TIMESTAMP,
    ban_reason            VARCHAR(500),
    suspended             BOOLEAN       DEFAULT FALSE NOT NULL,
    suspended_until       TIMESTAMP,
    suspend_reason        VARCHAR(500),
    created_at            TIMESTAMP     DEFAULT NOW() NOT NULL,
    updated_at            TIMESTAMP     DEFAULT NOW() NOT NULL
);

-- =========================================================
-- materials
-- =========================================================
CREATE TABLE materials (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id           BIGINT        NOT NULL REFERENCES users(id),
    title               VARCHAR(200)  NOT NULL,
    description         TEXT,
    price               INTEGER       NOT NULL CHECK (price >= 0 AND price <= 500000),
    subject             VARCHAR(50),
    professor           VARCHAR(50),
    category            VARCHAR(20),
    department          VARCHAR(50),
    semester            VARCHAR(20),
    file_type           VARCHAR(50),
    pages               INTEGER       DEFAULT 0 NOT NULL,
    file_count          INTEGER       DEFAULT 0 NOT NULL,
    file_key            VARCHAR(500),
    file_url            VARCHAR(1000),
    file_name           VARCHAR(200),
    file_size           BIGINT,
    content_type        VARCHAR(100),
    thumbnail           VARCHAR(1000),
    sales_count         INTEGER       DEFAULT 0 NOT NULL,
    view_count          INTEGER       DEFAULT 0 NOT NULL,
    grade_image         VARCHAR(1000),
    grade_claim         VARCHAR(10),
    grade_status        VARCHAR(20),
    verified_grade      VARCHAR(10),
    scan_status         VARCHAR(20)   DEFAULT 'pending' NOT NULL,
    hidden              BOOLEAN       DEFAULT FALSE NOT NULL,
    copyright_deleted   BOOLEAN       DEFAULT FALSE NOT NULL,
    created_at          TIMESTAMP     DEFAULT NOW() NOT NULL,
    updated_at          TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_material_author  ON materials(author_id);
CREATE INDEX idx_material_created ON materials(created_at DESC);
CREATE INDEX idx_material_hidden  ON materials(hidden, copyright_deleted);

-- 자료 파일 목록 (다중 파일, 최대 10개)
CREATE TABLE material_files (
    material_id  BIGINT        NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
    idx          INTEGER       NOT NULL,
    file_url     VARCHAR(1000),
    file_key     VARCHAR(500),
    file_name    VARCHAR(200),
    file_size    BIGINT,
    file_type    VARCHAR(50),
    PRIMARY KEY (material_id, idx)
);

-- 자료 미리보기 이미지
CREATE TABLE material_preview_images (
    material_id  BIGINT        NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
    idx          INTEGER       NOT NULL,
    url          VARCHAR(1000),
    PRIMARY KEY (material_id, idx)
);

-- =========================================================
-- purchases
-- =========================================================
CREATE TABLE purchases (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id      BIGINT        NOT NULL REFERENCES users(id),
    seller_id     BIGINT        NOT NULL REFERENCES users(id),
    material_id   BIGINT        NOT NULL REFERENCES materials(id),
    price         INTEGER       NOT NULL,
    settled       BOOLEAN       DEFAULT FALSE NOT NULL,
    downloaded    BOOLEAN       DEFAULT FALSE NOT NULL,
    downloaded_at TIMESTAMP,
    refunded      BOOLEAN       DEFAULT FALSE NOT NULL,
    refunded_at   TIMESTAMP,
    refund_reason VARCHAR(100),
    created_at    TIMESTAMP     DEFAULT NOW() NOT NULL,
    CONSTRAINT uq_buyer_material UNIQUE (buyer_id, material_id)
);

CREATE INDEX idx_purchase_buyer    ON purchases(buyer_id, created_at DESC);
CREATE INDEX idx_purchase_settled  ON purchases(settled, created_at);

-- =========================================================
-- transactions
-- =========================================================
CREATE TABLE transactions (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT        NOT NULL REFERENCES users(id),
    type                 VARCHAR(30)   NOT NULL,
    amount               BIGINT        NOT NULL,
    balance_after        BIGINT,
    balance_type         VARCHAR(10),
    description          VARCHAR(500),
    status               VARCHAR(20)   DEFAULT 'completed' NOT NULL,
    kakaopay_tid         VARCHAR(100),
    toss_payment_key     VARCHAR(200),
    toss_payment_amount  BIGINT,
    fee                  BIGINT,
    commission           BIGINT,
    tax                  BIGINT,
    total_deduction      BIGINT,
    received             BIGINT,
    bank_name            VARCHAR(30),
    account_number       VARCHAR(30),
    account_holder       VARCHAR(50),
    related_material_id  BIGINT,
    related_user_id      BIGINT,
    granted_by           VARCHAR(128),
    completed_by         VARCHAR(128),
    completed_at         TIMESTAMP,
    rejected_by          VARCHAR(128),
    rejected_at          TIMESTAMP,
    reject_reason        VARCHAR(500),
    created_at           TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_tx_user_created ON transactions(user_id, created_at DESC);
CREATE INDEX idx_tx_type_status  ON transactions(type, status);

-- =========================================================
-- reviews
-- =========================================================
CREATE TABLE reviews (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL REFERENCES users(id),
    material_id  BIGINT         NOT NULL REFERENCES materials(id),
    rating       INTEGER        NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content      VARCHAR(1000)  NOT NULL,
    created_at   TIMESTAMP      DEFAULT NOW() NOT NULL,
    CONSTRAINT uq_review_user_material UNIQUE (user_id, material_id)
);

CREATE INDEX idx_review_material ON reviews(material_id, created_at DESC);

-- =========================================================
-- reports
-- =========================================================
CREATE TABLE reports (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id      BIGINT         NOT NULL REFERENCES materials(id),
    reporter_id      BIGINT         NOT NULL REFERENCES users(id),
    type             VARCHAR(20)    NOT NULL,
    reason           VARCHAR(100)   NOT NULL,
    description      TEXT,
    original_source  VARCHAR(500),
    contact_email    VARCHAR(200),
    is_rights_holder BOOLEAN        DEFAULT FALSE NOT NULL,
    purchase_id      BIGINT,
    status           VARCHAR(20)    DEFAULT 'pending' NOT NULL,
    resolution       VARCHAR(50),
    resolved_by      VARCHAR(128),
    resolved_at      TIMESTAMP,
    created_at       TIMESTAMP      DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_report_status ON reports(status, created_at DESC);

-- =========================================================
-- withdraw_secrets (민감정보 — 운영에서는 앱단 AES-GCM 암호화 필수)
-- =========================================================
CREATE TABLE withdraw_secrets (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT        NOT NULL UNIQUE REFERENCES transactions(id),
    user_id         BIGINT        NOT NULL,
    bank_name       VARCHAR(30)   NOT NULL,
    account_number  VARCHAR(200)  NOT NULL,  -- 암호화 후 저장 (ciphertext + IV + tag)
    account_holder  VARCHAR(50)   NOT NULL,
    created_at      TIMESTAMP     DEFAULT NOW() NOT NULL
);

-- =========================================================
-- notifications
-- =========================================================
CREATE TABLE notifications (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES users(id),
    type            VARCHAR(30)   NOT NULL,
    title           VARCHAR(200)  NOT NULL,
    message         VARCHAR(500)  NOT NULL,
    material_id     BIGINT,
    material_title  VARCHAR(200),
    is_read         BOOLEAN       DEFAULT FALSE NOT NULL,
    created_at      TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_notif_user ON notifications(user_id, created_at DESC);

-- =========================================================
-- admin_logs (JSONB — PostgreSQL 네이티브)
-- =========================================================
CREATE TABLE admin_logs (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_uid  VARCHAR(128)  NOT NULL,
    action     VARCHAR(50)   NOT NULL,
    details    JSONB,
    created_at TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_admin_log_created ON admin_logs(created_at DESC);

-- =========================================================
-- cart (장바구니)
-- =========================================================
CREATE TABLE cart (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES users(id),
    material_id     BIGINT        NOT NULL,
    title           VARCHAR(200)  NOT NULL,
    price           INTEGER       NOT NULL,
    author          VARCHAR(100),
    category        VARCHAR(20),
    thumbnail       VARCHAR(1000),
    added_at        TIMESTAMP     DEFAULT NOW() NOT NULL,
    CONSTRAINT uq_cart_user_material UNIQUE (user_id, material_id)
);

CREATE INDEX idx_cart_user ON cart(user_id);

-- =========================================================
-- payment_sessions (결제 세션)
-- =========================================================
CREATE TABLE payment_sessions (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES users(id),
    type            VARCHAR(20)   NOT NULL,
    amount          BIGINT        NOT NULL,
    point_amount    BIGINT        NOT NULL,
    status          VARCHAR(20)   DEFAULT 'pending' NOT NULL,
    external_id     VARCHAR(200),
    created_at      TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_payment_session_user     ON payment_sessions(user_id);
CREATE INDEX idx_payment_session_external ON payment_sessions(external_id);

-- =========================================================
-- verification_sessions (SMS 인증 세션)
-- =========================================================
CREATE TABLE verification_sessions (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           VARCHAR(20)   NOT NULL,
    name            VARCHAR(50),
    code_hash       VARCHAR(128)  NOT NULL,
    expires_at      TIMESTAMP     NOT NULL,
    attempts        INTEGER       DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_verification_phone ON verification_sessions(phone);

-- =========================================================
-- material_requests (자료 요청)
-- =========================================================
CREATE TABLE material_requests (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES users(id),
    nickname        VARCHAR(16)   NOT NULL,
    subject         VARCHAR(50)   NOT NULL,
    professor       VARCHAR(50),
    description     TEXT,
    category        VARCHAR(20),
    need_count      INTEGER       DEFAULT 1 NOT NULL,
    status          VARCHAR(20)   DEFAULT 'open' NOT NULL,
    created_at      TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_material_request_user    ON material_requests(user_id);
CREATE INDEX idx_material_request_created ON material_requests(created_at DESC);

-- =========================================================
-- material_request_comments (자료 요청 댓글)
-- =========================================================
CREATE TABLE material_request_comments (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      BIGINT         NOT NULL REFERENCES material_requests(id) ON DELETE CASCADE,
    user_id         BIGINT         NOT NULL REFERENCES users(id),
    nickname        VARCHAR(16)    NOT NULL,
    content         VARCHAR(1000)  NOT NULL,
    created_at      TIMESTAMP      DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_mr_comment_request ON material_request_comments(request_id, created_at);

-- =========================================================
-- raffle_entries (래플 응모)
-- =========================================================
CREATE TABLE raffle_entries (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES users(id),
    product_id      VARCHAR(100)  NOT NULL,
    count           INTEGER       DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_raffle_user    ON raffle_entries(user_id);
CREATE INDEX idx_raffle_product ON raffle_entries(product_id);

-- =========================================================
-- charge_requests (계좌이체 충전 요청)
-- =========================================================
CREATE TABLE charge_requests (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT        NOT NULL REFERENCES users(id),
    email             VARCHAR(255)  NOT NULL,
    amount            BIGINT        NOT NULL,
    transfer_amount   BIGINT        NOT NULL,
    vat               BIGINT,
    sender_name       VARCHAR(50),
    sender_phone      VARCHAR(20),
    receipt_number    VARCHAR(100),
    receipt_type      VARCHAR(20),
    status            VARCHAR(20)   DEFAULT 'pending' NOT NULL,
    created_at        TIMESTAMP     DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_charge_request_user   ON charge_requests(user_id);
CREATE INDEX idx_charge_request_status ON charge_requests(status, created_at DESC);
