-- UniMarket Oracle Schema (23ai Free / ATP)
-- 참고: Oracle 23ai는 BOOLEAN, JSON 네이티브 타입을 지원
-- 실행 주체: APP_USER(UNIVMARKET)로 직접 접속해 실행해야 앱 스키마에 생성됨
-- (로컬 Docker는 backend/init-oracle.sh 래퍼가 APP_USER로 실행)

-- =========================================================
-- users
-- =========================================================
CREATE TABLE users (
    id                    NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid          VARCHAR2(128) NOT NULL UNIQUE,
    email                 VARCHAR2(255) NOT NULL,
    display_name          VARCHAR2(100),
    nickname              VARCHAR2(16)  UNIQUE,
    university            VARCHAR2(50),
    points                NUMBER(12,0)  DEFAULT 0 NOT NULL,
    earnings              NUMBER(12,0)  DEFAULT 0 NOT NULL,
    pending_earnings      NUMBER(12,0)  DEFAULT 0 NOT NULL,
    total_earned          NUMBER(12,0)  DEFAULT 0 NOT NULL,
    total_spent           NUMBER(12,0)  DEFAULT 0 NOT NULL,
    role                  VARCHAR2(10)  DEFAULT 'user' NOT NULL,
    identity_verified     BOOLEAN       DEFAULT FALSE NOT NULL,
    identity_verified_at  TIMESTAMP,
    verified_name         VARCHAR2(50),
    verified_phone        VARCHAR2(20),
    verified_birth        VARCHAR2(6),
    banned                BOOLEAN       DEFAULT FALSE NOT NULL,
    banned_at             TIMESTAMP,
    ban_reason            VARCHAR2(500),
    suspended             BOOLEAN       DEFAULT FALSE NOT NULL,
    suspended_until       TIMESTAMP,
    suspend_reason        VARCHAR2(500),
    created_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- =========================================================
-- materials
-- =========================================================
CREATE TABLE materials (
    id                  NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id           NUMBER(19)    NOT NULL REFERENCES users(id),
    title               VARCHAR2(200) NOT NULL,
    description         CLOB,
    price               NUMBER(10)    NOT NULL CHECK (price >= 0 AND price <= 500000),
    subject             VARCHAR2(50),
    professor           VARCHAR2(50),
    category            VARCHAR2(20),
    department          VARCHAR2(50),
    semester            VARCHAR2(20),
    file_type           VARCHAR2(50),
    pages               NUMBER(10)    DEFAULT 0 NOT NULL,
    file_count          NUMBER(10)    DEFAULT 0 NOT NULL,
    file_key            VARCHAR2(500),
    file_url            VARCHAR2(1000),
    file_name           VARCHAR2(200),
    file_size           NUMBER(19),
    content_type        VARCHAR2(100),
    thumbnail           VARCHAR2(1000),
    sales_count         NUMBER(10)    DEFAULT 0 NOT NULL,
    view_count          NUMBER(10)    DEFAULT 0 NOT NULL,
    grade_image         VARCHAR2(1000),
    grade_claim         VARCHAR2(10),
    grade_status        VARCHAR2(20),
    verified_grade      VARCHAR2(10),
    scan_status         VARCHAR2(20)  DEFAULT 'pending' NOT NULL,
    hidden              BOOLEAN       DEFAULT FALSE NOT NULL,
    copyright_deleted   BOOLEAN       DEFAULT FALSE NOT NULL,
    created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_material_author  ON materials(author_id);
CREATE INDEX idx_material_created ON materials(created_at DESC);
CREATE INDEX idx_material_hidden  ON materials(hidden, copyright_deleted);

-- 자료 파일 목록 (다중 파일, 최대 10개)
CREATE TABLE material_files (
    material_id  NUMBER(19)    NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
    idx          NUMBER(10)    NOT NULL,
    file_url     VARCHAR2(1000),
    file_key     VARCHAR2(500),
    file_name    VARCHAR2(200),
    file_size    NUMBER(19),
    file_type    VARCHAR2(50),
    PRIMARY KEY (material_id, idx)
);

-- 자료 미리보기 이미지
CREATE TABLE material_preview_images (
    material_id  NUMBER(19)     NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
    idx          NUMBER(10)     NOT NULL,
    url          VARCHAR2(1000),
    PRIMARY KEY (material_id, idx)
);

-- =========================================================
-- purchases
-- =========================================================
CREATE TABLE purchases (
    id            NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id      NUMBER(19)    NOT NULL REFERENCES users(id),
    seller_id     NUMBER(19)    NOT NULL REFERENCES users(id),
    material_id   NUMBER(19)    NOT NULL REFERENCES materials(id),
    price         NUMBER(10)    NOT NULL,
    settled       BOOLEAN       DEFAULT FALSE NOT NULL,
    downloaded    BOOLEAN       DEFAULT FALSE NOT NULL,
    downloaded_at TIMESTAMP,
    refunded      BOOLEAN       DEFAULT FALSE NOT NULL,
    refunded_at   TIMESTAMP,
    refund_reason VARCHAR2(100),
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_buyer_material UNIQUE (buyer_id, material_id)
);

CREATE INDEX idx_purchase_buyer    ON purchases(buyer_id, created_at DESC);
CREATE INDEX idx_purchase_settled  ON purchases(settled, created_at);

-- =========================================================
-- transactions
-- =========================================================
CREATE TABLE transactions (
    id                   NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER(19)    NOT NULL REFERENCES users(id),
    type                 VARCHAR2(30)  NOT NULL,
    amount               NUMBER(12,0)  NOT NULL,
    balance_after        NUMBER(12,0),
    balance_type         VARCHAR2(10),
    description          VARCHAR2(500),
    status               VARCHAR2(20)  DEFAULT 'completed' NOT NULL,
    kakaopay_tid         VARCHAR2(100),
    toss_payment_key     VARCHAR2(200),
    toss_payment_amount  NUMBER(12,0),
    fee                  NUMBER(12,0),
    commission           NUMBER(12,0),
    tax                  NUMBER(12,0),
    total_deduction      NUMBER(12,0),
    received             NUMBER(12,0),
    bank_name            VARCHAR2(30),
    account_number       VARCHAR2(30),
    account_holder       VARCHAR2(50),
    related_material_id  NUMBER(19),
    related_user_id      NUMBER(19),
    granted_by           VARCHAR2(128),
    completed_by         VARCHAR2(128),
    completed_at         TIMESTAMP,
    rejected_by          VARCHAR2(128),
    rejected_at          TIMESTAMP,
    reject_reason        VARCHAR2(500),
    created_at           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_tx_user_created ON transactions(user_id, created_at DESC);
CREATE INDEX idx_tx_type_status  ON transactions(type, status);

-- =========================================================
-- reviews
-- =========================================================
CREATE TABLE reviews (
    id           NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER(19)     NOT NULL REFERENCES users(id),
    material_id  NUMBER(19)     NOT NULL REFERENCES materials(id),
    rating       NUMBER(10)     NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content      VARCHAR2(1000) NOT NULL,
    created_at   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_review_user_material UNIQUE (user_id, material_id)
);

CREATE INDEX idx_review_material ON reviews(material_id, created_at DESC);

-- =========================================================
-- reports
-- =========================================================
CREATE TABLE reports (
    id               NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id      NUMBER(19)     NOT NULL REFERENCES materials(id),
    reporter_id      NUMBER(19)     NOT NULL REFERENCES users(id),
    type             VARCHAR2(20)   NOT NULL,
    reason           VARCHAR2(100)  NOT NULL,
    description      CLOB,
    original_source  VARCHAR2(500),
    contact_email    VARCHAR2(200),
    is_rights_holder BOOLEAN        DEFAULT FALSE NOT NULL,
    purchase_id      NUMBER(19),
    status           VARCHAR2(20)   DEFAULT 'pending' NOT NULL,
    resolution       VARCHAR2(50),
    resolved_by      VARCHAR2(128),
    resolved_at      TIMESTAMP,
    created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_report_status ON reports(status, created_at DESC);

-- =========================================================
-- withdraw_secrets (민감정보 — 운영에서는 앱단 AES-GCM 암호화 필수)
-- =========================================================
CREATE TABLE withdraw_secrets (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  NUMBER(19)    NOT NULL UNIQUE REFERENCES transactions(id),
    user_id         NUMBER(19)    NOT NULL,
    bank_name       VARCHAR2(30)  NOT NULL,
    account_number  VARCHAR2(200) NOT NULL,  -- 암호화 후 저장 (ciphertext + IV + tag)
    account_holder  VARCHAR2(50)  NOT NULL,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- =========================================================
-- notifications
-- =========================================================
CREATE TABLE notifications (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19)    NOT NULL REFERENCES users(id),
    type            VARCHAR2(30)  NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    message         VARCHAR2(500) NOT NULL,
    material_id     NUMBER(19),
    material_title  VARCHAR2(200),
    is_read         BOOLEAN       DEFAULT FALSE NOT NULL,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_notif_user ON notifications(user_id, created_at DESC);

-- =========================================================
-- admin_logs (JSON 네이티브 타입 사용 — 23ai)
-- =========================================================
CREATE TABLE admin_logs (
    id         NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_uid  VARCHAR2(128) NOT NULL,
    action     VARCHAR2(50)  NOT NULL,
    details    JSON,
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_admin_log_created ON admin_logs(created_at DESC);

-- =========================================================
-- cart (장바구니)
-- =========================================================
CREATE TABLE cart (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19)    NOT NULL REFERENCES users(id),
    material_id     NUMBER(19)    NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    price           NUMBER(10)    NOT NULL,
    author          VARCHAR2(100),
    category        VARCHAR2(20),
    thumbnail       VARCHAR2(1000),
    added_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_cart_user_material UNIQUE (user_id, material_id)
);

CREATE INDEX idx_cart_user ON cart(user_id);

-- =========================================================
-- payment_sessions (결제 세션)
-- =========================================================
CREATE TABLE payment_sessions (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19)    NOT NULL REFERENCES users(id),
    type            VARCHAR2(20)  NOT NULL,
    amount          NUMBER(12,0)  NOT NULL,
    point_amount    NUMBER(12,0)  NOT NULL,
    status          VARCHAR2(20)  DEFAULT 'pending' NOT NULL,
    external_id     VARCHAR2(200),
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_payment_session_user     ON payment_sessions(user_id);
CREATE INDEX idx_payment_session_external ON payment_sessions(external_id);

-- =========================================================
-- verification_sessions (SMS 인증 세션)
-- =========================================================
CREATE TABLE verification_sessions (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           VARCHAR2(20)  NOT NULL,
    name            VARCHAR2(50),
    code_hash       VARCHAR2(128) NOT NULL,
    expires_at      TIMESTAMP     NOT NULL,
    attempts        NUMBER(10)    DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_verification_phone ON verification_sessions(phone);

-- =========================================================
-- material_requests (자료 요청)
-- =========================================================
CREATE TABLE material_requests (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19)    NOT NULL REFERENCES users(id),
    nickname        VARCHAR2(16)  NOT NULL,
    subject         VARCHAR2(50)  NOT NULL,
    professor       VARCHAR2(50),
    description     CLOB,
    category        VARCHAR2(20),
    need_count      NUMBER(10)    DEFAULT 1 NOT NULL,
    status          VARCHAR2(20)  DEFAULT 'open' NOT NULL,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_material_request_user    ON material_requests(user_id);
CREATE INDEX idx_material_request_created ON material_requests(created_at DESC);

-- =========================================================
-- material_request_comments (자료 요청 댓글)
-- =========================================================
CREATE TABLE material_request_comments (
    id              NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      NUMBER(19)     NOT NULL REFERENCES material_requests(id) ON DELETE CASCADE,
    user_id         NUMBER(19)     NOT NULL REFERENCES users(id),
    nickname        VARCHAR2(16)   NOT NULL,
    content         VARCHAR2(1000) NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_mr_comment_request ON material_request_comments(request_id, created_at);

-- =========================================================
-- raffle_entries (래플 응모)
-- =========================================================
CREATE TABLE raffle_entries (
    id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19)    NOT NULL REFERENCES users(id),
    product_id      VARCHAR2(100) NOT NULL,
    count           NUMBER(10)    DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_raffle_user    ON raffle_entries(user_id);
CREATE INDEX idx_raffle_product ON raffle_entries(product_id);

-- =========================================================
-- charge_requests (계좌이체 충전 요청)
-- =========================================================
CREATE TABLE charge_requests (
    id                NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER(19)    NOT NULL REFERENCES users(id),
    email             VARCHAR2(255) NOT NULL,
    amount            NUMBER(12,0)  NOT NULL,
    transfer_amount   NUMBER(12,0)  NOT NULL,
    vat               NUMBER(12,0),
    sender_name       VARCHAR2(50),
    sender_phone      VARCHAR2(20),
    receipt_number    VARCHAR2(100),
    receipt_type      VARCHAR2(20),
    status            VARCHAR2(20)  DEFAULT 'pending' NOT NULL,
    created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_charge_request_user   ON charge_requests(user_id);
CREATE INDEX idx_charge_request_status ON charge_requests(status, created_at DESC);
